name: Swift Format Fix and Commit

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  swift-format:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Needed to push changes

    - name: Install swift-format
      run: |
        brew install swift-format

    - name: Run swift-format and fix issues
      run: |
        swift-format --in-place --recursive .

    - name: Commit and push changes if any
      run: |
        if [[ $(git status --porcelain) ]]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply swift-format"
          git push origin HEAD:${{ github.head_ref }}
        else
          echo "No formatting changes to commit."
        fi
